---
- hosts: all
  pre_tasks:
    - assert:
        that:
          - ansible_version.major == 2
  become: yes
  become_method: sudo
  roles:
    # This is not run yet b/c fdisk partitioning not automated yet --> see roles/lvm/tasks/main.yaml comment
    # - lvm
    - base
