# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "http://cis-kickstart.cisco.com/ccs-rhel-7.box"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../deploy.yaml"
    ansible.verbose = "vv"
  end
end
