---
# Docker devicemapper guide
# https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/


# Setup
- stat: path=/etc/systemd/system/docker.service.d/lvmblock.conf
  register: mybool

#- service: name=docker state=stopped
#  when: mybool.stat.exists

- name: Remove the /var/lib/docker cache path
  file: dest=/var/lib/docker/ state=absent
  when: mybool.stat.exists


# LVM
- name: Setup sdb as our docker vol group
  lvg: vg=docker state=present pvs=/dev/sdb

- name: Create a logical volume 95% of docker vg on /dev/sdb
  lvol: vg=docker lv=thinpool size=95%VG opts="--wipesignatures y"

- name: Create a logical volume 1% of docker vg on/dev/sdb
  lvol: vg=docker lv=thinpoolmeta size=1%VG opts="--wipesignatures y"

- name: Convert to thinpool
  command: "lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta"

- name: Create docker-thinpool.profile for pv, vs, and lv to use
  copy: src=docker-thinpool.profile dest=/etc/lvm/profile/docker-thinpool.profile mode=0400

- name: Apply new LVM profile
  command: lvchange --metadataprofile docker-thinpool docker/thinpool


# SystemD
- name: Create a docker.service.d systemd path
  file: dest='/etc/systemd/system/docker.service.d' mode=0700 state=directory

- name: Create an lvmblock.conf file for systemd docker.service.d
  copy: src=lvmblock.conf dest=/etc/systemd/system/docker.service.d/lvmblock.conf mode=0400


# Start it up
- name: Reload systemd daemon and start docker and check docker for return
  command: "systemctl daemon-reload;systemctl start docker;docker ps"
  when: mybool.stat.exists
